controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_base_mid
      - joint_mid_top
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - left_gripper_joint
      - right_gripper_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: up
  - group: hand
    pose: open