# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_base_mid
    - joint_mid_top
    - left_gripper_joint
    - right_gripper_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_base_mid
    - joint_mid_top
  gains:
    joint_base_mid:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_mid_top:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: position_controllers/JointPositionController
  joints:
    - left_gripper_joint
    - right_gripper_joint
  gains:
    left_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1